### ISSUE TITLE
WKWebView open inside app. asking for re-authentication.

### ISSUE THREAD

**Issue by zzdravkin** [Azure-Samples/active-directory-b2c-ios-swift-native-msal#50] opened 2021-03-24 18:53 UTC
After authenticated with any method, and opening WKWebView (new instance or shared singleton) webview is asking for sign-in.

Is there any way to sign in with the access token without showing sign-in page?

Even with SFSafariViewController and login page set to .default, still is showing sign-in page in SFSafariViewController

**Comment by hieunguyenmsft** [comment] 2021-03-25 22:43
If you have valid access token, you can try to sign-in silently with this API:
[Silent API](https://azuread.github.io/microsoft-authentication-library-for-objc/Classes/MSALPublicClientApplication.html#/c:objc(cs)MSALPublicClientApplication(im)acquireTokenSilentWithParameters:completionBlock:)
`-acquireTokenWithParameters:completionBlock:` always pops-up webview, it's by design.
Thanks

**Comment by zzdravkin** [comment] 2021-03-26 06:50
Scenario: 
1. App. open and I sign-in silently. I have the access token.
2. After I open WKWebView or SFSafariViewController and once I open the page, it asking for sign-in inside the WebView.

Any way to by-pass that sign in, maybe with javascript or cookies or any idea you can suggest


Thank you

**Comment by ameyapat** [comment] 2021-03-26 14:57
@zzdravkin SSO/ cookies are not shared in SFSafariViewController or WKWebView. https://docs.microsoft.com/en-us/azure/active-directory/develop/customize-webviews#cookie-sharing-and-single-sign-on-sso-implications

Can you use [ASWebAuthenticationSession](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession)?

**Comment by zzdravkin** [comment] 2021-03-26 17:11
Hi,

I am using 
 webViewParamaters?.webviewType = .authenticationSession or webViewParamaters?.webviewType = .default to sing-in which is using ASWebAuthenticationSession.

after that application start, and I want to open wkwebview or sfsafariViewController that will open a secure website but is asking for login again.

For example on the web, when you sign in and if you open a new tab, you are still signed in.

Sorry one more question, on the documentation it's says SSO is supported with "w/ Safari instances" is this to open Safari app and open the website from there or can use SFSafariViewController, because I tried all options and still asking to sign-in.

**Comment by ameyapat** [comment] 2021-03-30 22:42
@zzdravkin If you use ASWebAuthenticationSession you should have SSO in safari app. If you use WKWebView or SFSafariViewController safari app won't have SSO. Using WKWebView or SFSafariViewController will not provide SSO.

**Comment by zzdravkin** [comment] 2021-03-31 06:52
Hi Ameya Patil, Thanks for your answer.
Even when I use:
 `webViewParamaters?.webviewType = .authenticationSession`

and trying to open a link with the Safari app.
`UIApplication.shared.open(url)`

still asking for login.

So I guess SSO is not supported with iOS 13/14 as I've tried all combinations.
Any suggestions will be helpfull

Thank you

**Comment by ameyapat** [comment] 2021-03-31 15:23
Hi @zzdravkin,it should work for iOS 13 if you're using ASWebAuthenticationSession. 
Due to a bug from Apple in iOS 14, SSO is not working across b2c user flows but is fixed in iOS 14.5.
A workaround in that case is to enable [kmsi](https://docs.microsoft.com/en-us/azure/active-directory-b2c/session-behavior?pivots=b2c-user-flow#enable-keep-me-signed-in-kmsi)

**Comment by zzdravkin** [comment] 2021-03-31 18:16
Thank you for clearing it up

**Closed** 2021-04-01 19:39 UTC
Labels: question
