### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by mbondoso** [Azure-Samples/active-directory-b2c-ios-swift-native-msal#45] opened 2020-12-04 19:47 UTC
Hi, when trying to archive the app, I am getting this error:

A shell task (/usr/bin/xcrun lipo -remove x86_64 -output /var/folders/gk/yy0jdqss6q9g2cbg50vr77w00000gn/T/TemporaryItems/(A\ Document\ Being\ Saved\ By\ carthage\ 108)/carthage-lipo-zffIFN/MSAL.framework.dSYM/Contents/Resources/DWARF/MSAL /var/folders/gk/yy0jdqss6q9g2cbg50vr77w00000gn/T/TemporaryItems/(A\ Document\ Being\ Saved\ By\ carthage\ 108)/carthage-lipo-zffIFN/MSAL.framework.dSYM/Contents/Resources/DWARF/MSAL) failed with exit code 1:

Showing Recent Messages
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: input file (/var/folders/gk/yy0jdqss6q9g2cbg50vr77w00000gn/T/TemporaryItems/(A Document Being Saved By carthage 108)/carthage-lipo-zffIFN/MSAL.framework.dSYM/Contents/Resources/DWARF/MSAL) must be a fat file when the -remove option is specified

Command PhaseScriptExecution failed with a nonzero exit code

Has anyone been able to surpass this?

**Comment by NerevarineRule** [comment] 2020-12-04 23:24
Are you seeing this issue only on MSAL, or on other libraries. Thanks.

**Comment by mbondoso** [comment] 2020-12-04 23:56
Msal is our only lib dependency so yes.

**Comment by oldalton** [comment] 2020-12-08 23:02
Thanks for clarification. I'd recommend opening this issue in Carthage: https://github.com/Carthage/Carthage
Do you see any specific MSAL error in Carthage output?

**Comment by mbondoso** [comment] 2020-12-21 10:01
@oldalton Yes, this happens in the copy frameworks build phase.
I've removed the copy frameworks step but now I get this: ITMS-90338: Non-public API usage - The app references non-public selectors in XXXX: idToken, initWithParentViewController:, removeAccount:error:. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed.

**Comment by oldalton** [comment] 2020-12-21 15:21
Duplicate of https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/1155.

**Comment by ameyapat** [comment] 2020-12-22 23:20
Closing as duplicate of above stated issue

**Closed by ameyapat** 2020-12-22 23:20 UTC
Labels: question
